const app=document.getElementById('app'),langButton=document.getElementById('lang-toggle');
let lang=localStorage.getItem('wg_lang')||'ru',cfg={artworks:[]},stops=[];
const L={ru:{tag:'Выставка, которую перемещают зрители.',map:'КАРТА, КОТОРУЮ РИСУЕТ ВЫСТАВКА',works:'РАБОТЫ В ПУТИ',back:'← Все работы',history:'ИСТОРИЯ ПЕРЕМЕЩЕНИЙ',move:'ПЕРЕМЕСТИЛИ РАБОТУ?',intro:'Найдите новое место в Яндекс Картах, скопируйте ссылку и оставьте название места. На сайте оно станет новой остановкой собственной карты галереи.',place:'Название места',ymap:'Ссылка из Яндекс Карт',openY:'Открыть Яндекс Карты ↗',hint:'Яндекс Карты → найдите место → Поделиться → Скопировать ссылку.',send:'Добавить остановку',empty:'Работа ещё не начала путь.',ok:'Новая остановка добавлена.',walking:'работ в пути',stops:'экспозиций',comment:'Комментарий',schematic:'Это не обычная карта города. Она возникает только из мест, где побывали работы.',openPlace:'Открыть место в Яндекс Картах ↗'},en:{tag:'An exhibition moved by its viewers.',map:'THE MAP DRAWN BY THE EXHIBITION',works:'ARTWORKS WALKING',back:'← All artworks',history:'MOVEMENT HISTORY',move:'DID YOU MOVE IT?',intro:'Find the new place in Yandex Maps, copy its link and name the place. It will become a new stop on the gallery’s own map.',place:'Place name',ymap:'Yandex Maps link',openY:'Open Yandex Maps ↗',hint:'Yandex Maps → find the place → Share → Copy link.',send:'Add stop',empty:'This artwork has not started walking yet.',ok:'New stop added.',walking:'artworks walking',stops:'exhibitions',comment:'Comment',schematic:'This is not a normal city map. It appears only from places visited by the artworks.',openPlace:'Open in Yandex Maps ↗'}};
const t=k=>L[lang][k]||k,esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
langButton.onclick=()=>{lang=lang==='ru'?'en':'ru';localStorage.setItem('wg_lang',lang);render()};
boot();
async function boot(){const [a,b]=await Promise.all([fetch('/content/walking-gallery.json').then(r=>r.json()),fetch('/.netlify/functions/wg-data').then(r=>r.ok?r.json():{stops:[]}).catch(()=>({stops:[]}))]);cfg=a;stops=b.stops||[];render()}
function slug(){const p=location.pathname.split('/').filter(Boolean);return p[0]==='wg'&&p[1]?p[1]:''}
function artStops(id){return stops.filter(s=>s.artworkId===id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
function render(){document.documentElement.lang=lang;langButton.textContent=lang==='ru'?'EN':'RU';const s=slug(),a=cfg.artworks.find(x=>x.slug===s);a?detail(a):home()}
function home(){const active=new Set(stops.map(s=>s.artworkId)).size;app.innerHTML=`<section class="wg-hero"><div class="wg-shell"><div class="wg-kicker"><span>SONYAE_WG</span><span>2026</span></div><h1>SONYA'S<br>WALKING<br>GALLERY</h1><div class="wg-lede"><p>${t('tag')}</p><p>${t('schematic')}</p></div></div></section><div class="wg-shell"><section class="wg-stats"><div class="wg-stat"><strong>${active}</strong><span>${t('walking')}</span></div><div class="wg-stat"><strong>${stops.length}</strong><span>${t('stops')}</span></div></section></div><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('map')}</h2></div><div id="wg-map"></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('works')}</h2></div><div class="wg-artworks">${cfg.artworks.map(card).join('')}</div></div></section>`;requestAnimationFrame(mapAll)}
function card(a){const s=artStops(a.id),last=s.at(-1);return `<a class="wg-art-card" href="/wg/${a.slug}/"><span>${esc(a.id)}</span><h3>${esc(lang==='ru'?a.titleRu:a.titleEn)}</h3><div class="wg-art-card__meta"><span>${esc(last?last.locationLabel:t('empty'))}</span><span>→</span></div></a>`}
function mapAll(){const e=document.getElementById('wg-map'),m=new SchematicMap(e),routes=[];cfg.artworks.forEach(a=>{const p=artStops(a.id);if(p.length)routes.push({title:a.id,href:'/wg/'+a.slug+'/',points:p.map((x,i)=>({...x,markerLabel:String(i+1)}))})});m.setRoutes(routes)}
function detail(a){const s=artStops(a.id),last=s.at(-1);app.innerHTML=`<section class="wg-detail-hero"><div class="wg-shell"><a class="wg-back" href="/wg/">${t('back')}</a><div class="wg-detail-title"><h1>${esc(a.id)}</h1></div><div class="wg-current"><div><small>${t('stops')}</small><strong>${s.length}</strong></div><div><small>NOW</small><strong>${esc(last?last.locationLabel:t('empty'))}</strong></div></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('map')}</h2></div><div id="wg-map"></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('history')}</h2></div>${s.length?s.map((x,i)=>`<div class="wg-stop"><div>${String(i+1).padStart(2,'0')}</div><div><strong>${esc(x.locationLabel)}</strong><p>${new Date(x.createdAt).toLocaleDateString()}</p>${x.note?`<p>${esc(x.note)}</p>`:''}${x.mapUrl?`<p><a href="${esc(x.mapUrl)}" target="_blank" rel="noopener">${t('openPlace')}</a></p>`:''}</div></div>`).join(''):`<p>${t('empty')}</p>`}</div></section><section class="wg-section"><div class="wg-shell wg-form-wrap"><div><h2>${t('move')}</h2><p>${t('intro')}</p><a class="wg-yandex-link" href="https://yandex.ru/maps/" target="_blank" rel="noopener">${t('openY')}</a><p class="wg-hint">${t('hint')}</p></div><form class="wg-form" id="move"><div class="wg-field"><label for="place">${t('place')}</label><input id="place" maxlength="160" required placeholder="${lang==='ru'?'например: Чистые пруды, Москва':'e.g. Chistye Prudy, Moscow'}"></div><div class="wg-field"><label for="mapurl">${t('ymap')}</label><input id="mapurl" type="url" maxlength="500" placeholder="https://yandex.ru/maps/..."></div><div class="wg-field"><label for="note">${t('comment')}</label><textarea id="note" maxlength="500"></textarea></div><button class="wg-btn" type="submit">${t('send')}</button><div class="wg-message" id="msg"></div></form></div></section>`;requestAnimationFrame(()=>{mapOne(s);wire(a)})}
function mapOne(s){const e=document.getElementById('wg-map'),m=new SchematicMap(e),p=s.map((x,i)=>({...x,markerLabel:String(i+1)}));m.setRoutes(p.length?[{title:'ROUTE',points:p}]:[])}
function wire(a){const form=document.getElementById('move'),msg=document.getElementById('msg');form.onsubmit=async e=>{e.preventDefault();const payload={artworkId:a.id,locationLabel:document.getElementById('place').value.trim(),mapUrl:document.getElementById('mapurl').value.trim(),note:document.getElementById('note').value,formStartedAt:Date.now()-5000};const r=await fetch('/.netlify/functions/wg-submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();msg.textContent=r.ok&&d.ok?t('ok'):(d.error||'Error');msg.className='wg-message is-visible';if(r.ok&&d.ok)setTimeout(()=>location.reload(),700)}}
