const app=document.getElementById('app'),langButton=document.getElementById('lang-toggle');
let lang=localStorage.getItem('wg_lang')||'ru',cfg={artworks:[]},stops=[],lastReq=0;
const L={ru:{tag:'Выставка, которую перемещают зрители.',map:'КАРТА ВЫСТАВКИ',works:'РАБОТЫ В ПУТИ',back:'← Все работы',history:'ИСТОРИЯ ПЕРЕМЕЩЕНИЙ',move:'ПЕРЕМЕСТИЛИ РАБОТУ?',intro:'Выберите публичное место, где работа находится сейчас. Сайт сохраняет объект OpenStreetMap, а не GPS зрителя.',search:'Найти место',pick:'Выберите результат',send:'Добавить остановку',empty:'Работа ещё не начала путь.',ok:'Новая остановка добавлена.',walking:'работ в пути',stops:'экспозиций'},en:{tag:'An exhibition moved by its viewers.',map:'EXHIBITION MAP',works:'ARTWORKS WALKING',back:'← All artworks',history:'MOVEMENT HISTORY',move:'DID YOU MOVE IT?',intro:'Choose the public place where the artwork is now. The site stores an OpenStreetMap feature, not the viewer’s GPS position.',search:'Find a place',pick:'Choose a result',send:'Add stop',empty:'This artwork has not started walking yet.',ok:'New stop added.',walking:'artworks walking',stops:'exhibitions'}};
const t=k=>L[lang][k]||k,esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
langButton.onclick=()=>{lang=lang==='ru'?'en':'ru';localStorage.setItem('wg_lang',lang);render()};
boot();
async function boot(){const [a,b]=await Promise.all([fetch('/content/walking-gallery.json').then(r=>r.json()),fetch('/.netlify/functions/wg-data').then(r=>r.ok?r.json():{stops:[]}).catch(()=>({stops:[]}))]);cfg=a;stops=b.stops||[];await resolve();render()}
function slug(){let p=location.pathname.split('/').filter(Boolean);return p[0]==='wg'&&p[1]?p[1]:''}
function artStops(id){return stops.filter(s=>s.artworkId===id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
function ref(x){return ({node:'N',way:'W',relation:'R'}[x.osm_type]||'')+x.osm_id}
async function nom(url){let wait=Math.max(0,1050-(Date.now()-lastReq));if(wait)await new Promise(r=>setTimeout(r,wait));lastReq=Date.now();let r=await fetch(url);if(!r.ok)throw Error('Map search unavailable');return r.json()}
async function resolve(){let ids=[...new Set(stops.map(s=>s.osmRef).filter(Boolean))];if(!ids.length)return;let cache={};try{cache=JSON.parse(localStorage.getItem('wg_osm_cache')||'{}')}catch{}let miss=ids.filter(x=>!cache[x]);if(miss.length){try{let d=await nom('https://nominatim.openstreetmap.org/lookup?format=jsonv2&osm_ids='+encodeURIComponent(miss.slice(0,50).join(',')));d.forEach(x=>cache[ref(x)]={lat:+x.lat,lon:+x.lon});localStorage.setItem('wg_osm_cache',JSON.stringify(cache))}catch{}}stops=stops.map(s=>cache[s.osmRef]?{...s,...cache[s.osmRef]}:s)}
function render(){document.documentElement.lang=lang;langButton.textContent=lang==='ru'?'EN':'RU';let s=slug(),a=cfg.artworks.find(x=>x.slug===s);a?detail(a):home()}
function home(){let active=new Set(stops.map(s=>s.artworkId)).size;app.innerHTML=`<section class="wg-hero"><div class="wg-shell"><div class="wg-kicker"><span>SONYAE_WG</span><span>2026</span></div><h1>SONYA'S<br>WALKING<br>GALLERY</h1><div class="wg-lede"><p>${t('tag')}</p><p>Каждая новая точка — новая экспозиция работы.</p></div></div></section><div class="wg-shell"><section class="wg-stats"><div class="wg-stat"><strong>${active}</strong><span>${t('walking')}</span></div><div class="wg-stat"><strong>${stops.length}</strong><span>${t('stops')}</span></div></section></div><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('map')}</h2></div><div id="wg-map"></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('works')}</h2></div><div class="wg-artworks">${cfg.artworks.map(card).join('')}</div></div></section>`;requestAnimationFrame(mapAll)}
function card(a){let s=artStops(a.id),last=s.at(-1);return `<a class="wg-art-card" href="/wg/${a.slug}/"><span>${esc(a.id)}</span><h3>${esc(lang==='ru'?a.titleRu:a.titleEn)}</h3><div class="wg-art-card__meta"><span>${esc(last?last.locationLabel:t('empty'))}</span><span>→</span></div></a>`}
function mapAll(){let e=document.getElementById('wg-map'),m=new WalkingMap(e,{zoom:3}),routes=[],pts=[];cfg.artworks.forEach(a=>{let p=artStops(a.id).filter(x=>Number.isFinite(x.lat));if(p.length){pts.push(...p);routes.push({href:'/wg/'+a.slug+'/',points:p.map(x=>({...x,markerLabel:a.slug}))})}});m.setRoutes(routes);if(pts.length)m.fitPoints(pts)}
function detail(a){let s=artStops(a.id),last=s.at(-1);app.innerHTML=`<section class="wg-detail-hero"><div class="wg-shell"><a class="wg-back" href="/wg/">${t('back')}</a><div class="wg-detail-title"><h1>${esc(a.id)}</h1></div><div class="wg-current"><div><small>${t('stops')}</small><strong>${s.length}</strong></div><div><small>NOW</small><strong>${esc(last?last.locationLabel:t('empty'))}</strong></div></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('map')}</h2></div><div id="wg-map"></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('history')}</h2></div>${s.length?s.map((x,i)=>`<div class="wg-stop"><div>${String(i+1).padStart(2,'0')}</div><div><strong>${esc(x.locationLabel)}</strong><p>${new Date(x.createdAt).toLocaleDateString()}</p>${x.note?`<p>${esc(x.note)}</p>`:''}</div></div>`).join(''):`<p>${t('empty')}</p>`}</div></section><section class="wg-section"><div class="wg-shell wg-form-wrap"><div><h2>${t('move')}</h2><p>${t('intro')}</p></div><form class="wg-form" id="move"><div class="wg-field"><label>${t('search')}</label><div class="wg-searchrow"><input id="q"><button class="wg-btn" type="button" id="find">${t('search')}</button></div></div><div id="results"></div><div id="choice"></div><div class="wg-field"><label>Комментарий</label><textarea id="note" maxlength="500"></textarea></div><button class="wg-btn" type="submit">${t('send')}</button><div class="wg-message" id="msg"></div></form></div></section>`;requestAnimationFrame(()=>{mapOne(s);wire(a)})}
function mapOne(s){let e=document.getElementById('wg-map'),m=new WalkingMap(e,{zoom:4}),p=s.filter(x=>Number.isFinite(x.lat));if(p.length){m.setRoutes([{points:p.map((x,i)=>({...x,markerLabel:String(i+1)}))}]);m.fitPoints(p)}}
function wire(a){let chosen=null,form=document.getElementById('move'),results=document.getElementById('results'),choice=document.getElementById('choice'),msg=document.getElementById('msg');document.getElementById('find').onclick=async()=>{let q=document.getElementById('q').value.trim();if(!q)return;results.textContent='…';try{let d=await nom('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+encodeURIComponent(q));results.innerHTML=d.map((x,i)=>`<button class="wg-place" type="button" data-i="${i}">${esc(x.display_name)}</button>`).join('');results.querySelectorAll('button').forEach(b=>b.onclick=()=>{let x=d[+b.dataset.i];chosen={osmRef:ref(x),locationLabel:x.display_name};choice.innerHTML=`<div class="wg-choice">${esc(x.display_name)}</div>`;results.innerHTML=''})}catch(e){results.textContent=e.message}};form.onsubmit=async e=>{e.preventDefault();if(!chosen){msg.textContent=t('pick');msg.className='wg-message is-visible';return}let payload={artworkId:a.id,...chosen,note:document.getElementById('note').value,formStartedAt:Date.now()-5000};let r=await fetch('/.netlify/functions/wg-submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();msg.textContent=r.ok&&d.ok?t('ok'):(d.error||'Error');msg.className='wg-message is-visible';if(r.ok&&d.ok)setTimeout(()=>location.reload(),700)}}
