const app=document.getElementById('app'),langButton=document.getElementById('lang-toggle');
let lang=localStorage.getItem('wg_lang')||'ru',cfg={artworks:[]},stops=[];
if(!document.querySelector('link[data-wg-mobile]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/wg/mobile.css';l.dataset.wgMobile='1';document.head.appendChild(l)}
const L={ru:{tag:'Выставка, которую перемещают зрители.',map:'КАРТА, КОТОРУЮ РИСУЕТ ВЫСТАВКА',works:'РАБОТЫ В ПУТИ',back:'← Все работы',history:'ИСТОРИЯ ПЕРЕМЕЩЕНИЙ',move:'ПЕРЕМЕСТИЛИ РАБОТУ?',intro:'Найдите новое место в Яндекс Картах и нажмите «Поделиться → Скопировать». Сюда можно вставить всё, что скопировал Яндекс — сайт сам отделит адрес от ссылки.',place:'Название места',share:'Скопированное из Яндекс Карт',paste:'ВСТАВИТЬ ИЗ БУФЕРА',pasteHint:'Можно вставить весь текст целиком. Ничего удалять вручную не нужно.',linkFound:'Ссылка на Яндекс Карты найдена ✓',noLink:'Ссылка не найдена. Название места всё равно можно сохранить.',clipFail:'Браузер не дал доступ к буферу. Нажмите на поле и выберите «Вставить».',openY:'Открыть Яндекс Карты ↗',send:'Добавить остановку',empty:'Работа ещё не начала путь.',ok:'Новая остановка добавлена.',walking:'работ в пути',stops:'экспозиций',comment:'Комментарий',schematic:'Это не обычная карта города. Она возникает только из мест, где побывали работы.',openPlace:'Открыть место в Яндекс Картах ↗',imagePending:'ИЗОБРАЖЕНИЕ РАБОТЫ'},en:{tag:'An exhibition moved by its viewers.',map:'THE MAP DRAWN BY THE EXHIBITION',works:'ARTWORKS WALKING',back:'← All artworks',history:'MOVEMENT HISTORY',move:'DID YOU MOVE IT?',intro:'Find the new place in Yandex Maps and choose Share → Copy. Paste everything Yandex copied here — the site will separate the place name from the link.',place:'Place name',share:'Copied from Yandex Maps',paste:'PASTE FROM CLIPBOARD',pasteHint:'Paste the whole copied text. You do not need to clean it up.',linkFound:'Yandex Maps link found ✓',noLink:'No link found. You can still save the place name.',clipFail:'The browser could not read the clipboard. Tap the field and choose Paste.',openY:'Open Yandex Maps ↗',send:'Add stop',empty:'This artwork has not started walking yet.',ok:'New stop added.',walking:'artworks walking',stops:'exhibitions',comment:'Comment',schematic:'This is not a normal city map. It appears only from places visited by the artworks.',openPlace:'Open in Yandex Maps ↗',imagePending:'ARTWORK IMAGE'}};
const t=k=>L[lang][k]||k,esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const artVisual=(a,card=false)=>a.image?`<div class="${card?'wg-art-card__image':'wg-artwork-visual'}"><img src="${esc(a.image)}" alt="${esc(lang==='ru'?a.titleRu:a.titleEn)}" loading="lazy"></div>`:`<div class="${card?'wg-art-card__image ':'wg-artwork-visual '}wg-artwork-image--pending"><span>${esc(a.id)}</span><small>${t('imagePending')}</small></div>`;
langButton.onclick=()=>{lang=lang==='ru'?'en':'ru';localStorage.setItem('wg_lang',lang);render()};
boot();
async function boot(){const [a,b]=await Promise.all([fetch('/content/walking-gallery.json').then(r=>r.json()),fetch('/.netlify/functions/wg-data').then(r=>r.ok?r.json():{stops:[]}).catch(()=>({stops:[]}))]);cfg=a;stops=b.stops||[];render()}
function slug(){const p=location.pathname.split('/').filter(Boolean);return p[0]==='wg'&&p[1]?p[1]:''}
function artStops(id){return stops.filter(s=>s.artworkId===id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
function parseYandex(raw){const text=String(raw||'').trim();const m=text.match(/https?:\/\/(?:www\.)?(?:(?:yandex\.(?:ru|com)(?:\/maps)?)|ya\.cc)\/[^\s]+/i);let url=m?m[0].replace(/[\]\[),.;!?]+$/,''):'';let rest=(m?text.replace(m[0],' '):text).replace(/\s*[—-]\s*(?:Яндекс\s*Карты|Yandex\s*Maps)\s*$/i,'').trim();const lines=rest.split(/\n+/).map(x=>x.trim()).filter(Boolean).filter(x=>!/^(?:Яндекс\s*Карты|Yandex\s*Maps|Поделиться|Share)$/i.test(x));return {url,name:(lines[0]||'').slice(0,160)}}
function render(){document.documentElement.lang=lang;langButton.textContent=lang==='ru'?'EN':'RU';const s=slug(),a=cfg.artworks.find(x=>x.slug===s);a?detail(a):home()}
function home(){const active=new Set(stops.map(s=>s.artworkId)).size;app.innerHTML=`<section class="wg-hero"><div class="wg-shell"><div class="wg-kicker"><span>SONYAE_WG</span><span>2026</span></div><h1>SONYA'S<br>WALKING<br>GALLERY</h1><div class="wg-lede"><p>${t('tag')}</p><p>${t('schematic')}</p></div></div></section><div class="wg-shell"><section class="wg-stats"><div class="wg-stat"><strong>${active}</strong><span>${t('walking')}</span></div><div class="wg-stat"><strong>${stops.length}</strong><span>${t('stops')}</span></div></section></div><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('map')}</h2></div><div id="wg-map"></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('works')}</h2></div><div class="wg-artworks">${cfg.artworks.map(card).join('')}</div></div></section>`;requestAnimationFrame(mapAll)}
function card(a){const s=artStops(a.id),last=s.at(-1);return `<a class="wg-art-card" href="/wg/${a.slug}/">${artVisual(a,true)}<span>${esc(a.id)}</span><h3>${esc(lang==='ru'?a.titleRu:a.titleEn)}</h3><div class="wg-art-card__meta"><span>${esc(last?last.locationLabel:t('empty'))}</span><span>→</span></div></a>`}
function mapAll(){const e=document.getElementById('wg-map'),m=new SchematicMap(e),routes=[];cfg.artworks.forEach(a=>{const p=artStops(a.id);if(p.length)routes.push({title:a.id,href:'/wg/'+a.slug+'/',points:p.map((x,i)=>({...x,markerLabel:String(i+1)}))})});m.setRoutes(routes)}
function detail(a){const s=artStops(a.id),last=s.at(-1);app.innerHTML=`<section class="wg-detail-hero"><div class="wg-shell"><a class="wg-back" href="/wg/">${t('back')}</a><div class="wg-detail-title"><h1>${esc(a.id)}</h1></div>${artVisual(a)}<div class="wg-current"><div><small>${t('stops')}</small><strong>${s.length}</strong></div><div><small>NOW</small><strong>${esc(last?last.locationLabel:t('empty'))}</strong></div></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('map')}</h2></div><div id="wg-map"></div></div></section><section class="wg-section"><div class="wg-shell"><div class="wg-section__head"><h2>${t('history')}</h2></div>${s.length?s.map((x,i)=>`<div class="wg-stop"><div>${String(i+1).padStart(2,'0')}</div><div><strong>${esc(x.locationLabel)}</strong><p>${new Date(x.createdAt).toLocaleDateString()}</p>${x.note?`<p>${esc(x.note)}</p>`:''}${x.mapUrl?`<p><a href="${esc(x.mapUrl)}" target="_blank" rel="noopener">${t('openPlace')}</a></p>`:''}</div></div>`).join(''):`<p>${t('empty')}</p>`}</div></section><section class="wg-section"><div class="wg-shell wg-form-wrap"><div><h2>${t('move')}</h2><p>${t('intro')}</p><a class="wg-yandex-link" href="https://yandex.ru/maps/" target="_blank" rel="noopener">${t('openY')}</a></div><form class="wg-form" id="move"><div class="wg-field"><label for="share">${t('share')}</label><div class="wg-paste-row"><textarea id="share" maxlength="1000" placeholder="${t('pasteHint')}"></textarea><button class="wg-btn wg-btn--secondary" type="button" id="paste">${t('paste')}</button></div><div class="wg-paste-state" id="paste-state"></div></div><div class="wg-field"><label for="place">${t('place')}</label><input id="place" maxlength="160" required placeholder="${lang==='ru'?'например: Ховрино, Москва':'e.g. Khovrino, Moscow'}"></div><div class="wg-field"><label for="note">${t('comment')}</label><textarea id="note" maxlength="500"></textarea></div><button class="wg-btn" type="submit">${t('send')}</button><div class="wg-message" id="msg"></div></form></div></section>`;requestAnimationFrame(()=>{mapOne(s);wire(a)})}
function mapOne(s){const e=document.getElementById('wg-map'),m=new SchematicMap(e),p=s.map((x,i)=>({...x,markerLabel:String(i+1)}));m.setRoutes(p.length?[{title:'ROUTE',points:p}]:[])}
function wire(a){const form=document.getElementById('move'),msg=document.getElementById('msg'),share=document.getElementById('share'),place=document.getElementById('place'),state=document.getElementById('paste-state'),paste=document.getElementById('paste');let placeEdited=false;place.addEventListener('input',()=>placeEdited=true);const process=()=>{const p=parseYandex(share.value);if(p.name&&!placeEdited)place.value=p.name;state.textContent=p.url?t('linkFound'):(share.value.trim()?t('noLink'):'');state.className='wg-paste-state'+(p.url?' is-ok':'');return p};share.addEventListener('input',process);paste.onclick=async()=>{try{share.value=await navigator.clipboard.readText();process()}catch{state.textContent=t('clipFail');state.className='wg-paste-state'}};place.addEventListener('paste',e=>{const text=e.clipboardData?.getData('text')||'';if(/https?:\/\//i.test(text)){e.preventDefault();share.value=text;placeEdited=false;process()}});form.onsubmit=async e=>{e.preventDefault();const parsed=process(),payload={artworkId:a.id,locationLabel:place.value.trim()||parsed.name,mapUrl:parsed.url,note:document.getElementById('note').value,formStartedAt:Date.now()-5000};const r=await fetch('/.netlify/functions/wg-submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();msg.textContent=r.ok&&d.ok?t('ok'):(d.error||'Error');msg.className='wg-message is-visible';if(r.ok&&d.ok)setTimeout(()=>location.reload(),700)}}
